// This file will be regenerated by kysely-codegen
// Import generated types once they are available
import type { DB } from './types';

// Re-export for convenience
export type { DB };

// Convenience type exports
export type Language = DB['languages'];
export type NewLanguage = Omit<DB['languages'], 'id'>;

export type TranslationKey = DB['translation_keys'];
export type NewTranslationKey = Omit<DB['translation_keys'], 'id'>;

export type Translation = DB['translations'];
export type NewTranslation = Omit<DB['translations'], 'id'>;
