/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Languages {
  code: string;
  id: Generated<number>;
  name: string;
}

export interface TranslationKeyPaths {
  full_path: string | null;
  id: number | null;
}

export interface TranslationKeys {
  description: string | null;
  id: Generated<number>;
  key: string;
  parent_id: number | null;
}

export interface Translations {
  id: Generated<number>;
  key_id: number;
  language_code: string;
  value: string;
}

export interface DB {
  languages: Languages;
  translation_key_paths: TranslationKeyPaths;
  translation_keys: TranslationKeys;
  translations: Translations;
}
